/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import model.ChartCreater;
import model.InfoDownload;
import model.User;

import org.jfree.chart.ChartPanel;

/**
 *
 * @author Administrator
 */
public class ComInternalFrame extends javax.swing.JInternalFrame implements ActionListener {

    /**
     * Creates new form ComInternalFrame
     */
    public ComInternalFrame() {
    	super("对比", true, true, true, true);
        initComponents();
        initListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        comComboBox = new javax.swing.JComboBox();
        comTextField = new javax.swing.JTextField();
        comButton = new javax.swing.JButton();
        cPanel = new ChartPanel(null);

        setPreferredSize(new java.awt.Dimension(750, 530));

        comComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "按时间", "按分类" }));

        comTextField.setPreferredSize(new java.awt.Dimension(100, 21));

        comButton.setText("添加");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(cPanel);
        cPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(comTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comButton)
                        .addGap(0, 123, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void initListener() {
    	comButton.addActionListener(this);
    	comComboBox.addActionListener(this);
    }
    
    @Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		if(e.getSource() == comButton) {
			String name = comTextField.getText();
			InfoDownload infodownload = new InfoDownload();
			if(infodownload.init(name)) {
				infodownload.getinfo();
				cc.add(new User(name));
				loadChart();
			}
			else {
				JOptionPane.showMessageDialog(null, "该用户不存在");
			}
			comTextField.setText("");
		}
		
		if(e.getSource() == comComboBox) {
			loadChart();
		}
	}
    
    public boolean loadChart() {
    	if(comComboBox.getSelectedIndex()==0)
    		cPanel.setChart(cc.getTimeChart());
    	else 
    		cPanel.setChart(cc.getTypeChart());
    	return true;
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton comButton;
    private javax.swing.JComboBox comComboBox;
    private javax.swing.JTextField comTextField;
    private ChartPanel cPanel;
    private ChartCreater cc = new ChartCreater();
    // End of variables declaration                   
}
